root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tx-aggregator ."
bin = "tx-aggregator"
full_bin = "./tx-aggregator"
include_ext = ["go", "tpl", "tmpl", "html", "yaml"]
exclude_dir = ["assets", "tmp", "vendor"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
log = "air.log"
env = ["APP_ENV=dev"]

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
