version: '3.8'

services:
  app-1:
    build: .
    ports:
      - "${APP_PORT1}:8050"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_PORT=${APP_PORT1}
      - CONSUL_ADDRESS=${CONSUL_ADDRESS}
      - CONSUL_SCHEME=${CONSUL_SCHEME}
      - CONSUL_DATACENTER=${CONSUL_DATACENTER}
      - CONSUL_TOKEN=${CONSUL_TOKEN}
      - SERVICE_NAME=${SERVICE_NAME}
      - SERVICE_IP=${SERVICE_IP}
      - SERVICE_PORT=${APP_PORT1}
    volumes:
      - ./configfiles:/app/configfiles
      - ./logs/app-1:/app/logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  app-2:
    build: .
    ports:
      - "${APP_PORT2}:8051"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_PORT=${APP_PORT2}
      - CONSUL_ADDRESS=${CONSUL_ADDRESS}
      - CONSUL_SCHEME=${CONSUL_SCHEME}
      - CONSUL_DATACENTER=${CONSUL_DATACENTER}
      - CONSUL_TOKEN=${CONSUL_TOKEN}
      - SERVICE_NAME=${SERVICE_NAME}
      - SERVICE_IP=${SERVICE_IP}
      - SERVICE_PORT=${APP_PORT2}
    volumes:
      - ./configfiles:/app/configfiles
      - ./logs/app-2:/app/logs
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
