version: '3.8'

services:
  app-1:
    build: .
    ports:
      - "9090:9090"
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - APP_PORT=9090
    volumes:
      - ./config:/app/config
      - ./consul:/app/consul
    restart: unless-stopped

  app-2:
    build: .
    ports:
      - "9091:9091"
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - APP_PORT=9091
    volumes:
      - ./config:/app/config
      - ./consul:/app/consul
    restart: unless-stopped
