version: '3.8'

services:
  app-1:
    build: .
    ports:
      - "8050:8050"
    environment:
      - APP_ENV=${APP_ENV:-test}
      - APP_PORT=8050
    volumes:
      - ./config:/app/config
      - ./consul:/app/consul
    restart: unless-stopped

  app-2:
    build: .
    ports:
      - "8051:8051"
    environment:
      - APP_ENV=${APP_ENV:-test}
      - APP_PORT=8051
    volumes:
      - ./config:/app/config
      - ./consul:/app/consul
    restart: unless-stopped
