version: '3.8'

services:
  app:
    build: .
    ports:
      - "${APP_PORT}:8050"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_PORT=${APP_PORT}
      - CONSUL_ADDRESS=${CONSUL_ADDRESS}
      - CONSUL_SCHEME=${CONSUL_SCHEME}
      - CONSUL_DATACENTER=${CONSUL_DATACENTER}
      - CONSUL_TOKEN=${CONSUL_TOKEN}
      - SERVICE_NAME=${SERVICE_NAME}
      - SERVICE_IP=${SERVICE_IP}
      - SERVICE_PORT=${APP_PORT}
    volumes:
      - ./configfiles:/app/configfiles
      - "${HOST_LOG_PATH}:/app/logs"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"


        