# config.yaml
# v1.4.8

# Server configuration
server:
  port: 8080  # Port number for the application server

# Redis cluster configuration
redis:
  addrs:  # List of Redis server addresses
    - 127.0.0.1:6379
  password: ""  # Redis authentication password (empty for no password)
  ttl: 60  # Time-to-live for cached data in seconds

# Providers configuration
providers:
  request_timeout: 60
  chain_providers:
    ETH: ankr
    BSC: ankr
    POL: ankr
    BASE: ankr
    TTX: blockscout_ttx
    HoleskyETH: ankr
    SepoliaETH: ankr
    AmoyPOL: ankr
    BaseSepoliaETH: ankr
    TestnetBSC: blockscan_testnetbsc
    TestnetTTX: blockscout_testnetttx

# Ankr API configuration for blockchain data
ankr:
  api_key: 15d9d6561619144cc7f0681a08055130110513f4d6f5bef0c1919af78c9f6a65  # Ankr API key for authentication
  url: https://rpc.ankr.com/multichain  # Ankr RPC endpoint URL
  chain_ids:
    eth: 1
    bsc: 56
    polygon: 137
    base : 8453
    eth_holesky: 17000
    eth_sepolia: 11155111
    polygon_amoy: 80002
    base_sepolia: 84532
  request_page_size: 100  # Number of records per API request

# Blockscout providers (multiple chain support)
blockscout:
  - url: https://api.tantin.com/api/v2
    chain_name: TTX
    request_page_size: 100
    rpc_url: https://rpc.tantin.com
    rpc_request_timeout: 90
  - url: http://testscan.tantin.com/api/v2/
    chain_name: TestnetTTX
    request_page_size: 100
    rpc_url: https://testrpc.tantin.com
    rpc_request_timeout: 90

# Blockscan providers for TestnetBSC
blockscan:
  - url: https://api-testnet.bscscan.com/api
    api_key: QW27JK8B2N7W4UME127Y2RW2PZF4CMDWJR
    chain_name: TestnetBSC
    request_page_size: 100

# Logging configuration
log:
  level: 0  # Log level (0: DEBUG, 1: INFO, 2: WARN, 3: ERROR)
  path: ./logs  # Directory for log files
  console_format: text # Log format for console output (text or json)
  file_format: json  # Log format (text or json)

# Response configuration
response:
  max: 50  # Maximum number of items in API response

# Chain ID mapping for different blockchain networks
chain_names:
  ETH: 1
  BSC: 56
  POL: 137
  BASE: 8453
  TTX: 12301
  HoleskyETH: 17000
  SepoliaETH: 11155111
  AmoyPOL: 80002
  BaseSepoliaETH: 84532
  TestnetBSC: 97
  TestnetTTX: 12302

# Native token name mapping by chain ID
native_tokens:
  "1": ETH
  "56": BNB
  "137": POL
  "8453": ETH
  "12301": CTC
  "17000": HoleskyETH
  "11155111": SepoliaETH
  "80002": POL
  "84532": ETH
  "97": BNB
  "12302": CTC

