# config.yaml
# Version: v1.4.7

# ------------------------------
# Server configuration
# ------------------------------
server:
  port: 8080  # Port number for the application server

# ------------------------------
# Redis configuration (single-node or cluster)
# ------------------------------
redis:
  addrs:        # List of Redis server addresses
    - tantin-test-address-valkey.ttckps.ng.0001.apse1.cache.amazonaws.com:6379
  password: ""  # Redis authentication password (empty for no password)
  ttl: 60       # Time-to-live for cached data in seconds

# ------------------------------
# Data provider configuration
# ------------------------------
providers:
  request_timeout: 60
  chain_providers:
    ETH: ankr
    BSC: ankr
    POL: ankr
    BASE: ankr
    TTX: blockscout_ttx

# Ankr API configuration for blockchain data
ankr:
  api_key: 15d9d6561619144cc7f0681a08055130110513f4d6f5bef0c1919af78c9f6a65  # Ankr API key for authentication
  url: https://rpc.ankr.com/multichain  # Ankr RPC endpoint URL
  request_blockchains:  # List of supported blockchain networks
    - eth
    - bsc
    - polygon
    - base
  chain_ids:
    eth: 1
    bsc: 56
    polygon: 137
    base : 8453
  request_page_size: 100  # Number of records per API request

# Blockscout providers (multiple chain support)
blockscout:
  - url: https://api.tantin.com/api/v2
    chain_name: TTX
    request_page_size: 100
    rpc_url: https://rpc.tantin.com
    rpc_request_timeout: 90

# Logging configuration
log:
  level: 0  # Log level (0: DEBUG, 1: INFO, 2: WARN, 3: ERROR)
  path: /app/logs  # Directory for log files

# Response configuration
response:
  max: 50  # Maximum number of items in API response

# Chain ID mapping for different blockchain networks
chain_names:
  ETH: 1        # Ethereum mainnet
  BSC: 56       # Binance Smart Chain
  POL: 137      # Polygon (Matic)
  BASE: 8453    # Base Mainnet
  TTX: 12301   # Tantin chain ID

# Native token name mapping by chain ID
native_tokens:
  "1": ETH
  "56": BNB
  "137": POL
  "8453": ETH
  "12301": CTC
